### ISSUE TITLE
Mica 5.2+ gives unauthorized for MongoDB

### ISSUE THREAD

**Issue by tomkuipers1402** [obiba/docker-mica#10]
Hi,
I'm encountering issues with Mica 5.2+ & mongodb. I have a mongodb container + credentials, which are used by my Mica container. I used this setup for 5.0 & 5.1 & then Mica is able to communicate with mongo using this in application.yml:
mongodb://MONGO_USER:MONGO_PASSWORD@mongodbMica:27017/mica?authSource=admin
For Mica 5.2 & 5.3 this setup no longer works & I get unauthorized messages & Mica doesn't start up anymore.
I attached the Mica logs for you to check.
[mica.log](https://github.com/obiba/docker-mica/files/14330958/mica.log)

**Comment by ymarcon** [comment]
The mongodb [java driver 4.7 is compatible up to 6.0](https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/) so I do not see why their would be a problem. Any idea @kazoompa ?

**Comment by kazoompa** [comment]
Hi Tom,

I tried the following with a Mica 5.3.3 image and the server started up correctly:

```
version: '3'
services:
        mica:
                image: obiba/mica:latest
                ports:
                        - "9945:8445"
                        - "9982:8082"
                links:
                        - mongo
                        # - agate
                        # - opal
                environment:
                        - MICA_ADMINISTRATOR_PASSWORD=${MICA_ADMINISTRATOR_PASSWORD}
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - MONGO_USERNAME=toto
                        - MONGO_PASSWORD=toto1234
                        - OPAL_URL=https://opal-demo.obiba.org
                        - AGATE_URL=https://agate-demo.obiba.org
                volumes:
                        - ${MICA_DIR}:/srv
        mongo:
                image: mongo
                environment:
                        MONGO_INITDB_ROOT_USERNAME: toto
                        MONGO_INITDB_ROOT_PASSWORD: toto1234
```

 `MONGO_USER` should be `MONGO_USERNAME`.

**Comment by tomkuipers1402** [comment]
Your solution using MONGO_USERNAME & MONGO_PASSWORD in the mica environment works. I didn't know that was an option. I used to change the application.yml to:
```
spring:
    data:
        mongodb:
            uri: mongodb://toto:toto1234@mongo:27017/mica?authSource=admin
```
Normally that was enough, but this doesn't work anymore. When using your approach, the mongodb connections in application.yml stays at: `uri: mongodb://localhost:27017/mica`. Should that still be updated? Is there or should there be a difference in using the environment variables (which works) or changing the mongo string in application.yml (which no longer works)?

**Comment by tomkuipers1402** [comment]
In Agate I also need to update the mongodb connection string in Agate's application.yml, when having mongo credentials. So isn't it strange that this no longer works for Mica?

**Comment by tomkuipers1402** [comment]
Using this container btw: `mongo:6.0.2-focal`

**Comment by kazoompa** [comment]
It is inddeed curious, I need to investigate more.

I usually do not touch the `application.yml` when I build a OBiBa stack  via `docker-compose`. I find it more centralized doing such configurations in the compose file.

**Comment by tomkuipers1402** [comment]
Yes I agree, but since I already have to do it for Agate, I use that same script to update Mica. It seems that Agate doesn't work with these configurations in the compose? I tried to add:
```
- MONGO_USERNAME=toto
- MONGO_PASSWORD=toto1234
```
To Agate compose, but that gives unauthorized too:
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command aggregate requires authentication' on server mongodbagate:27017. The full response is {"ok": 0.0, "errmsg": "command aggregate requires authentication", "code": 13, "codeName": "Unauthorized"}
```
So in Mica I can't edit the application.yml, but can only give mongo credentials in compose. In Agate I can only edit the application.yml, but can't give mongo credentials in compose. Right?

**Comment by kazoompa** [comment]
Hi Tom,

In Agate do you also have:
```
 mongo:
                image: mongo
                environment:
                        MONGO_INITDB_ROOT_USERNAME: toto
                        MONGO_INITDB_ROOT_PASSWORD: toto1234
```
In your compose file?

**Comment by tomkuipers1402** [comment]
Yes:
```
version: '3'
services:
        agate:
                image: obiba/agate:2.8
                restart: "unless-stopped"
                environment:
                        - MONGO_HOST=mongodbAgate
                        - MONGO_PORT=27017
                        - MONGO_USERNAME=toto
                        - MONGO_PASSWORD=toto1234
                        - AGATE_ADMINISTRATOR_PASSWORD=password
                volumes:
                        - /obiba/agate/:/srv/

        mongodbAgate:
                image: mongo:6.0.2-focal
                restart: "unless-stopped"
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=toto
                        - MONGO_INITDB_ROOT_PASSWORD=toto1234
```
This gives:
```
Caused by: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'command aggregate requires authentication' on server mongodbagate:27017. The full response is {"ok": 0.0, "errmsg": "command aggregate requires authentication", "code": 13, "codeName": "Unauthorized"}
```
