### ISSUE TITLE
Mica gives 404 on adding table to collected dataset

### ISSUE THREAD

**Issue by tomkuipers1402** [obiba/docker-mica#11]
Using Mica 5.3.3
I created a test study & tried to add table to collected dataset:
Individual -> Collected Datasets -> Add dataset
Creating a dataset works. Then adding a table fails with 404 as soon as I select my study. Also my Opal datasource is not listed. This was a problem I have encountered before when using mongodb with credentials, but its also not working when leaving them out. My compose:
```
version: '3'
services:
        mica:
                image: obiba/mica:5.3
                restart: "unless-stopped"
                links:
                        - mongo
                        - agate
                        - opal
                environment:
                        - JAVA_OPTS=-Xmx2G
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - OPAL_URL=http://opal:8080
                        - AGATE_URL=http://agate:8081
        mongo:
                image: mongo:6.0.2-focal
                restart: "unless-stopped"
        opal:
                image: obiba/opal:4.6
                restart: "unless-stopped"
                links:
                        - mongo
                        - agate
                environment:
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - AGATE_URL=http://agate:8081
        agate:
                image: obiba/agate:2.8
                restart: "unless-stopped"
                links:
                        - mongo
                environment:
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
```
![Capture](https://github.com/obiba/docker-mica/assets/51093395/a70171bb-ccd8-4981-bdeb-b59790a64b2d)
From mica.log:
```
2024-03-11 12:50:32.359  INFO 69 --- [         task-7] o.obiba.mica.study.search.StudyIndexer   : Study Study{id=teststudy, name={en=testStudy}} was updated
2024-03-11 12:50:32.361 DEBUG 69 --- [         task-7] org.obiba.es.mica.ESIndexer              : Indexing for indexName [study-draft] indexableObject [Study{id=teststudy, name={en=testStudy}}]
2024-03-11 12:50:32.413  INFO 69 --- [ qtp55173478-19] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:7, serverValue:14}] to mongo:27017
2024-03-11 12:50:32.427  WARN 69 --- [ qtp55173478-91] o.obiba.core.translator.JsonTranslator   : Translation of study.access.access_cost_reduction_consideration.title is not valid path: Missing property in path $['study']['access']['access_cost_reduction_consideration']
```
From rest.log
```
{"@timestamp":"2024-03-11T12:56:33.760Z","@version":"1","message":"/config","logger_name":"org.obiba.mica.web.rest.security.AuditInterceptor","thread_name":"qtp55173478-18","level":"INFO","level_value":20000,"method":"GET","ip":"10.161.107.121","username":"administrator","status":"200"}
{"@timestamp":"2024-03-11T12:56:33.771Z","@version":"1","message":"/draft/study-states queryParams:{type: [individual-study]}","logger_name":"org.obiba.mica.web.rest.security.AuditInterceptor","thread_name":"qtp55173478-69","level":"INFO","level_value":20000,"method":"GET","ip":"10.161.107.121","username":"administrator","status":"200"}
{"@timestamp":"2024-03-11T12:56:33.774Z","@version":"1","message":"/draft/study-states queryParams:{type: [harmonization-study]}","logger_name":"org.obiba.mica.web.rest.security.AuditInterceptor","thread_name":"qtp55173478-25","level":"INFO","level_value":20000,"method":"GET","ip":"10.161.107.121","username":"administrator","status":"200"}
{"@timestamp":"2024-03-11T12:56:40.294Z","@version":"1","message":"/draft/study-state/teststudy/projects","logger_name":"org.obiba.mica.web.rest.security.AuditInterceptor","thread_name":"qtp55173478-92","level":"WARN","level_value":30000,"method":"GET","ip":"10.161.107.121","username":"administrator","status":"404"}
```
